### PR TITLE
cleaned up utilities.py

### PR DESCRIPTION
**Pull request by Datavenia**
Added a gitignore, commented failing smoke test (TODO). Utilities.py change was pretty simple.

All imports from os were in os.path. By importing those three things directly we keep the namespace uncluttered. Looking at invocations of REPO_ABS_DIR, this isn't in the hot path. Caching seems unnecessary lacking profiling data to the contrary.

### CODE REVIEW

**Comment by Datavenia** [comment]
Also fixed imports (everything wants to refer back to src right now, there's probably a way to not do that but right now IDK what it is) which allows the tests to all work. Added a test for edaplay.

**Comment by JulianKemmerer** [comment]
Hmm it doesnt seen to see the src with modules in it - I cloned your repo and got?
```
  File "./src/pipelinec", line 12, in <module>
    from src import C_TO_LOGIC,OPEN_TOOLS,SIM,SYN
ModuleNotFoundError: No module named 'src'
```

**Comment by Datavenia** [comment]
Okay seems we've got some OS funsies? I'll try to figure it out tomorrow

**Comment by Datavenia** [comment]
Making pytest work this way made everything else not work, obviously not a good way to do things.

**Pull request closed without merging**
